# Generated by Django 4.2.11 on 2026-05-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('general', 'Общее'), ('greeting', 'Приветствие'), ('payment', 'Оплата'), ('delivery', 'Доставка'), ('followup', 'Дожим'), ('other', 'Другое')], default='general', max_length=20)),
                ('emoji', models.CharField(default='💬', max_length=10)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
                'db_table': 'message_templates',
                'ordering': ['-use_count', '-created_at'],
            },
        ),
    ]
